# Generated by Django 3.1.5 on 2021-01-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                ("service_type", models.CharField(max_length=60)),
                ("customer", models.CharField(max_length=60)),
                ("csp", models.CharField(max_length=60)),
                ("cost", models.CharField(max_length=60)),
                ("result", models.CharField(max_length=60)),
                ("record_uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["creation_date"],
            },
        ),
    ]
