# Generated by Django 3.1.5 on 2021-01-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionrecord",
            name="cost",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("ATTRIBUTE SERVICE", "Attribute Service"),
                    ("DOCUMENT SERVICE", "Document Service"),
                    ("PHONE SERVICE", "Phone Service"),
                    ("PROOFING SERVICE", "Proofing Service"),
                    ("SENSOR SERVICE", "Sensor Service"),
                ],
                max_length=20,
            ),
        ),
    ]
