# Generated by Django 3.1.5 on 2021-01-29 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210115_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionrecord",
            name="record_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
