# Generated by Django 3.1.5 on 2021-03-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210129_0659"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionrecord",
            old_name="customer",
            new_name="provider",
        ),
    ]
