# Generated by Django 3.1.5 on 2021-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20210312_1738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionrecord",
            name="result",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
